WARNING    - 2023-08-29 16:36:28,690 - client          : PyNaCl is not installed, voice will NOT be supported
INFO       - 2023-08-29 16:36:28,691 - client          : logging in using static token
INFO       - 2023-08-29 16:36:29,927 - gateway         : Shard ID None has connected to Gateway (Session ID: e56a06dedf576ebd81e1312ab68586fc).
WARNING    - 2023-08-29 16:37:20,918 - gateway         : Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "/home/rhythm/python/schwi.py/main.py", line 37, in <module>
    run()
  File "/home/rhythm/python/schwi.py/main.py", line 33, in run
    bot.run(settings.DISCORD_API_SECRET, root_logger=True)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/usr/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/rhythm/python/schwi.py/main.py", line 19, in on_ready
    await bot.load_extension(f"cogs.{cog_file.name[:-3]}")
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1013, in load_extension
    await self._load_from_module_spec(spec, name)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 935, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rhythm/python/schwi.py/cogs/world.py", line 5, in <module>
    import utils.data
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rhythm/python/schwi.py/utils/data.py", line 38, in <module>
    for node in db.fog_collection.find():
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/cursor.py", line 1262, in next
    if len(self.__data) or self._refresh():
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/cursor.py", line 1202, in _refresh
    self.__send_message(g)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/cursor.py", line 1060, in __send_message
    response = client._run_operation(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1388, in _run_operation
    return self._retryable_read(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1535, in _retryable_read
    return func(session, server, conn, read_pref)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1384, in _cmd
    return server.run_operation(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/helpers.py", line 315, in inner
    return func(*args, **kwargs)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/server.py", line 155, in run_operation
    reply = conn.receive_message(request_id)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/pool.py", line 984, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/network.py", line 267, in receive_message
    data = _receive_data_on_socket(conn, length - 16, deadline)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/network.py", line 328, in _receive_data_on_socket
    chunk_length = conn.conn.recv_into(mv[bytes_read:])
  File "/usr/lib/python3.11/ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.11/ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)

WARNING    - 2023-08-29 16:37:30,919 - gateway         : Shard ID None heartbeat blocked for more than 20 seconds.
Loop thread traceback (most recent call last):
  File "/home/rhythm/python/schwi.py/main.py", line 37, in <module>
    run()
  File "/home/rhythm/python/schwi.py/main.py", line 33, in run
    bot.run(settings.DISCORD_API_SECRET, root_logger=True)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/usr/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/rhythm/python/schwi.py/main.py", line 19, in on_ready
    await bot.load_extension(f"cogs.{cog_file.name[:-3]}")
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1013, in load_extension
    await self._load_from_module_spec(spec, name)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 935, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rhythm/python/schwi.py/cogs/world.py", line 5, in <module>
    import utils.data
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rhythm/python/schwi.py/utils/data.py", line 38, in <module>
    for node in db.fog_collection.find():
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/cursor.py", line 1262, in next
    if len(self.__data) or self._refresh():
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/cursor.py", line 1202, in _refresh
    self.__send_message(g)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/cursor.py", line 1060, in __send_message
    response = client._run_operation(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1388, in _run_operation
    return self._retryable_read(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1535, in _retryable_read
    return func(session, server, conn, read_pref)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1384, in _cmd
    return server.run_operation(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/helpers.py", line 315, in inner
    return func(*args, **kwargs)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/server.py", line 155, in run_operation
    reply = conn.receive_message(request_id)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/pool.py", line 984, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/network.py", line 267, in receive_message
    data = _receive_data_on_socket(conn, length - 16, deadline)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/network.py", line 328, in _receive_data_on_socket
    chunk_length = conn.conn.recv_into(mv[bytes_read:])
  File "/usr/lib/python3.11/ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.11/ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)

WARNING    - 2023-08-29 16:37:40,920 - gateway         : Shard ID None heartbeat blocked for more than 30 seconds.
Loop thread traceback (most recent call last):
  File "/home/rhythm/python/schwi.py/main.py", line 37, in <module>
    run()
  File "/home/rhythm/python/schwi.py/main.py", line 33, in run
    bot.run(settings.DISCORD_API_SECRET, root_logger=True)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/usr/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/rhythm/python/schwi.py/main.py", line 19, in on_ready
    await bot.load_extension(f"cogs.{cog_file.name[:-3]}")
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1013, in load_extension
    await self._load_from_module_spec(spec, name)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 935, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rhythm/python/schwi.py/cogs/world.py", line 5, in <module>
    import utils.data
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rhythm/python/schwi.py/utils/data.py", line 38, in <module>
    for node in db.fog_collection.find():
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/cursor.py", line 1262, in next
    if len(self.__data) or self._refresh():
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/cursor.py", line 1202, in _refresh
    self.__send_message(g)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/cursor.py", line 1060, in __send_message
    response = client._run_operation(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1388, in _run_operation
    return self._retryable_read(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1535, in _retryable_read
    return func(session, server, conn, read_pref)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1384, in _cmd
    return server.run_operation(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/helpers.py", line 315, in inner
    return func(*args, **kwargs)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/server.py", line 155, in run_operation
    reply = conn.receive_message(request_id)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/pool.py", line 984, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/network.py", line 267, in receive_message
    data = _receive_data_on_socket(conn, length - 16, deadline)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/network.py", line 328, in _receive_data_on_socket
    chunk_length = conn.conn.recv_into(mv[bytes_read:])
  File "/usr/lib/python3.11/ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.11/ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)

WARNING    - 2023-08-29 16:37:50,924 - gateway         : Shard ID None heartbeat blocked for more than 40 seconds.
Loop thread traceback (most recent call last):
  File "/home/rhythm/python/schwi.py/main.py", line 37, in <module>
    run()
  File "/home/rhythm/python/schwi.py/main.py", line 33, in run
    bot.run(settings.DISCORD_API_SECRET, root_logger=True)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/usr/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/ext/tasks/__init__.py", line 239, in _loop
    await self.coro(*args, **kwargs)
  File "/home/rhythm/python/schwi.py/cogs/world.py", line 54, in game
    await update_command(c, client=self.client)
  File "/home/rhythm/python/schwi.py/utils/command_utils.py", line 723, in update_command
    units_collection.update_one(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/collection.py", line 1088, in update_one
    self._update_retryable(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/collection.py", line 883, in _update_retryable
    return self.__database.client._retryable_write(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1568, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1413, in _retry_with_session
    return self._retry_internal(retryable, func, session, bulk)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1460, in _retry_internal
    return func(session, conn, retryable)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/collection.py", line 864, in _update
    return self._update(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/collection.py", line 818, in _update
    result = conn.command(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/helpers.py", line 315, in inner
    return func(*args, **kwargs)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/pool.py", line 932, in command
    return command(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/network.py", line 181, in command
    reply = receive_message(conn, request_id)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/network.py", line 247, in receive_message
    length, _, response_to, op_code = _UNPACK_HEADER(_receive_data_on_socket(conn, 16, deadline))
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/network.py", line 328, in _receive_data_on_socket
    chunk_length = conn.conn.recv_into(mv[bytes_read:])
  File "/usr/lib/python3.11/ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.11/ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)

WARNING    - 2023-08-29 16:38:00,926 - gateway         : Shard ID None heartbeat blocked for more than 50 seconds.
Loop thread traceback (most recent call last):
  File "/home/rhythm/python/schwi.py/main.py", line 37, in <module>
    run()
  File "/home/rhythm/python/schwi.py/main.py", line 33, in run
    bot.run(settings.DISCORD_API_SECRET, root_logger=True)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/usr/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/ext/tasks/__init__.py", line 239, in _loop
    await self.coro(*args, **kwargs)
  File "/home/rhythm/python/schwi.py/cogs/world.py", line 104, in game
    db.units_collection.update_one(query, update)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/collection.py", line 1088, in update_one
    self._update_retryable(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/collection.py", line 883, in _update_retryable
    return self.__database.client._retryable_write(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1568, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1413, in _retry_with_session
    return self._retry_internal(retryable, func, session, bulk)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1460, in _retry_internal
    return func(session, conn, retryable)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/collection.py", line 864, in _update
    return self._update(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/collection.py", line 818, in _update
    result = conn.command(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/helpers.py", line 315, in inner
    return func(*args, **kwargs)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/pool.py", line 932, in command
    return command(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/network.py", line 181, in command
    reply = receive_message(conn, request_id)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/network.py", line 247, in receive_message
    length, _, response_to, op_code = _UNPACK_HEADER(_receive_data_on_socket(conn, 16, deadline))
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/network.py", line 328, in _receive_data_on_socket
    chunk_length = conn.conn.recv_into(mv[bytes_read:])
  File "/usr/lib/python3.11/ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.11/ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)

WARNING    - 2023-08-29 16:38:10,927 - gateway         : Shard ID None heartbeat blocked for more than 60 seconds.
Loop thread traceback (most recent call last):
  File "/home/rhythm/python/schwi.py/main.py", line 37, in <module>
    run()
  File "/home/rhythm/python/schwi.py/main.py", line 33, in run
    bot.run(settings.DISCORD_API_SECRET, root_logger=True)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/usr/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/ext/tasks/__init__.py", line 239, in _loop
    await self.coro(*args, **kwargs)
  File "/home/rhythm/python/schwi.py/cogs/world.py", line 106, in game
    db.fog_collection.bulk_write(fog_updates)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/collection.py", line 571, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/bulk.py", line 580, in execute
    return self.execute_command(generator, write_concern, session)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/bulk.py", line 447, in execute_command
    client._retry_with_session(self.is_retryable, retryable_bulk, s, self)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1413, in _retry_with_session
    return self._retry_internal(retryable, func, session, bulk)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1460, in _retry_internal
    return func(session, conn, retryable)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/bulk.py", line 435, in retryable_bulk
    self._execute_command(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/bulk.py", line 381, in _execute_command
    result, to_send = bwc.execute(cmd, ops, client)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/message.py", line 967, in execute
    result = self.write_command(cmd, request_id, msg, to_send)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/helpers.py", line 315, in inner
    return func(*args, **kwargs)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/message.py", line 1061, in write_command
    reply = self.conn.write_command(request_id, msg, self.codec)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/pool.py", line 1020, in write_command
    reply = self.receive_message(request_id)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/pool.py", line 984, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/network.py", line 247, in receive_message
    length, _, response_to, op_code = _UNPACK_HEADER(_receive_data_on_socket(conn, 16, deadline))
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/network.py", line 328, in _receive_data_on_socket
    chunk_length = conn.conn.recv_into(mv[bytes_read:])
  File "/usr/lib/python3.11/ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.11/ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)

INFO       - 2023-08-29 16:38:16,028 - gateway         : Shard ID None has successfully RESUMED session e56a06dedf576ebd81e1312ab68586fc.
WARNING    - 2023-08-29 16:39:07,120 - gateway         : Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "/home/rhythm/python/schwi.py/main.py", line 37, in <module>
    run()
  File "/home/rhythm/python/schwi.py/main.py", line 33, in run
    bot.run(settings.DISCORD_API_SECRET, root_logger=True)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/usr/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/ext/tasks/__init__.py", line 239, in _loop
    await self.coro(*args, **kwargs)
  File "/home/rhythm/python/schwi.py/cogs/world.py", line 104, in game
    db.units_collection.update_one(query, update)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/collection.py", line 1088, in update_one
    self._update_retryable(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/collection.py", line 883, in _update_retryable
    return self.__database.client._retryable_write(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1568, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1413, in _retry_with_session
    return self._retry_internal(retryable, func, session, bulk)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1460, in _retry_internal
    return func(session, conn, retryable)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/collection.py", line 864, in _update
    return self._update(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/collection.py", line 818, in _update
    result = conn.command(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/helpers.py", line 315, in inner
    return func(*args, **kwargs)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/pool.py", line 932, in command
    return command(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/network.py", line 181, in command
    reply = receive_message(conn, request_id)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/network.py", line 247, in receive_message
    length, _, response_to, op_code = _UNPACK_HEADER(_receive_data_on_socket(conn, 16, deadline))
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/network.py", line 328, in _receive_data_on_socket
    chunk_length = conn.conn.recv_into(mv[bytes_read:])
  File "/usr/lib/python3.11/ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.11/ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)

ERROR      - 2023-08-29 16:39:16,308 - client          : Attempting a reconnect in 0.23s
Traceback (most recent call last):
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/client.py", line 659, in connect
    await self.ws.poll_event()
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/gateway.py", line 646, in poll_event
    raise ConnectionClosed(self.socket, shard_id=self.shard_id, code=code) from None
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 1000
INFO       - 2023-08-29 16:39:17,406 - gateway         : Shard ID None has successfully RESUMED session e56a06dedf576ebd81e1312ab68586fc.
ERROR      - 2023-08-29 16:39:28,737 - view            : Ignoring exception in view <Construct_View timeout=40 children=1> for item <construct_Select placeholder='Select the building' min_values=1 max_values=1 disabled=False options=[<SelectOption label='Barracks' value='Barracks' description='Wood: 100 ,Stone: 100 ,Gold: 200 ,Iron: 200 ' emoji=None default=False>, <SelectOption label='Docks' value='Docks' description='Wood: 150 ,Stone: 50 ,Gold: 300 ,Iron: 100 ' emoji=None default=False>, <SelectOption label='Fishmonger' value='Fishmonger' description='Wood: 50 ,Stone: 50 ,Gold: 50 ,Iron: 0 ' emoji=None default=False>, <SelectOption label='Grain Stall' value='Grain Stall' description='Wood: 50 ,Stone: 50 ,Gold: 50 ,Iron: 0 ' emoji=None default=False>, <SelectOption label='Workshop' value='Workshop' description='Wood: 50 ,Stone: 200 ,Gold: 300 ,Iron: 300 ' emoji=None default=False>, <SelectOption label='Horizontal Wall' value='Horizontal Wall' description='Wood: 25 ,Stone: 50 ,Gold: 20 ,Iron: 0 ' emoji=None default=False>, <SelectOption label='Vertical Wall' value='Vertical Wall' description='Wood: 25 ,Stone: 50 ,Gold: 20 ,Iron: 0 ' emoji=None default=False>, <SelectOption label='Tower' value='Tower' description='Wood: 25 ,Stone: 50 ,Gold: 20 ,Iron: 0 ' emoji=None default=False>, <SelectOption label='Ladder Tower' value='Ladder Tower' description='Wood: 50 ,Stone: 50 ,Gold: 20 ,Iron: 0 ' emoji=None default=False>]>
Traceback (most recent call last):
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/ui/view.py", line 427, in _scheduled_task
    await item.callback(interaction)
  File "/home/rhythm/python/schwi.py/models/views.py", line 864, in callback
    fog_image.paste(building_image, draw_box, mask=building_image)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/PIL/Image.py", line 1732, in paste
    self.im.paste(im, box, mask.im)
ValueError: images do not match
WARNING    - 2023-08-29 16:40:08,491 - gateway         : Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "/home/rhythm/python/schwi.py/main.py", line 37, in <module>
    run()
  File "/home/rhythm/python/schwi.py/main.py", line 33, in run
    bot.run(settings.DISCORD_API_SECRET, root_logger=True)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/usr/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/ext/tasks/__init__.py", line 239, in _loop
    await self.coro(*args, **kwargs)
  File "/home/rhythm/python/schwi.py/cogs/world.py", line 104, in game
    db.units_collection.update_one(query, update)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/collection.py", line 1088, in update_one
    self._update_retryable(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/collection.py", line 883, in _update_retryable
    return self.__database.client._retryable_write(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1568, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1413, in _retry_with_session
    return self._retry_internal(retryable, func, session, bulk)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1460, in _retry_internal
    return func(session, conn, retryable)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/collection.py", line 864, in _update
    return self._update(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/collection.py", line 818, in _update
    result = conn.command(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/helpers.py", line 315, in inner
    return func(*args, **kwargs)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/pool.py", line 932, in command
    return command(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/network.py", line 181, in command
    reply = receive_message(conn, request_id)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/network.py", line 247, in receive_message
    length, _, response_to, op_code = _UNPACK_HEADER(_receive_data_on_socket(conn, 16, deadline))
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/network.py", line 328, in _receive_data_on_socket
    chunk_length = conn.conn.recv_into(mv[bytes_read:])
  File "/usr/lib/python3.11/ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.11/ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)

ERROR      - 2023-08-29 16:40:18,216 - client          : Attempting a reconnect in 1.77s
Traceback (most recent call last):
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/client.py", line 659, in connect
    await self.ws.poll_event()
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/gateway.py", line 646, in poll_event
    raise ConnectionClosed(self.socket, shard_id=self.shard_id, code=code) from None
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 1000
INFO       - 2023-08-29 16:40:20,517 - gateway         : Shard ID None has successfully RESUMED session e56a06dedf576ebd81e1312ab68586fc.
WARNING    - 2023-08-29 16:41:11,616 - gateway         : Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "/home/rhythm/python/schwi.py/main.py", line 37, in <module>
    run()
  File "/home/rhythm/python/schwi.py/main.py", line 33, in run
    bot.run(settings.DISCORD_API_SECRET, root_logger=True)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/usr/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/ext/tasks/__init__.py", line 239, in _loop
    await self.coro(*args, **kwargs)
  File "/home/rhythm/python/schwi.py/cogs/world.py", line 106, in game
    db.fog_collection.bulk_write(fog_updates)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/collection.py", line 571, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/bulk.py", line 580, in execute
    return self.execute_command(generator, write_concern, session)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/bulk.py", line 447, in execute_command
    client._retry_with_session(self.is_retryable, retryable_bulk, s, self)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1413, in _retry_with_session
    return self._retry_internal(retryable, func, session, bulk)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1460, in _retry_internal
    return func(session, conn, retryable)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/bulk.py", line 435, in retryable_bulk
    self._execute_command(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/bulk.py", line 381, in _execute_command
    result, to_send = bwc.execute(cmd, ops, client)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/message.py", line 967, in execute
    result = self.write_command(cmd, request_id, msg, to_send)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/helpers.py", line 315, in inner
    return func(*args, **kwargs)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/message.py", line 1061, in write_command
    reply = self.conn.write_command(request_id, msg, self.codec)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/pool.py", line 1020, in write_command
    reply = self.receive_message(request_id)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/pool.py", line 984, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/network.py", line 247, in receive_message
    length, _, response_to, op_code = _UNPACK_HEADER(_receive_data_on_socket(conn, 16, deadline))
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/network.py", line 328, in _receive_data_on_socket
    chunk_length = conn.conn.recv_into(mv[bytes_read:])
  File "/usr/lib/python3.11/ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.11/ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)

ERROR      - 2023-08-29 16:41:15,526 - client          : Attempting a reconnect in 2.74s
Traceback (most recent call last):
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/client.py", line 659, in connect
    await self.ws.poll_event()
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/gateway.py", line 646, in poll_event
    raise ConnectionClosed(self.socket, shard_id=self.shard_id, code=code) from None
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 1000
INFO       - 2023-08-29 16:41:18,836 - gateway         : Shard ID None has successfully RESUMED session e56a06dedf576ebd81e1312ab68586fc.
