WARNING    - 2023-08-11 15:58:27,197 - client          : PyNaCl is not installed, voice will NOT be supported
INFO       - 2023-08-11 15:58:27,198 - client          : logging in using static token
INFO       - 2023-08-11 15:58:29,940 - gateway         : Shard ID None has connected to Gateway (Session ID: e6155d169bc71e1fe3338c628efa16c5).
ERROR      - 2023-08-11 16:04:33,383 - view            : Ignoring exception in view <Select_View timeout=40 children=1> for item <Unit_Select placeholder='Select your command' min_values=1 max_values=1 disabled=False options=[<SelectOption label='Move' value='Move' description='Move this unit on the map.' emoji=<PartialEmoji animated=False name='location' id=1065283234834940044> default=False>, <SelectOption label='Turn' value='Turn' description='Choose the direction that your unit is facing.' emoji=<PartialEmoji animated=False name='turn' id=1135328996159131708> default=False>, <SelectOption label='Action' value='Action' description='Interact with nearby objects on the map.' emoji=<PartialEmoji animated=False name='pickaxe' id=1101437961414905898> default=False>, <SelectOption label='Attack (Unit)' value='Attack (Unit)' description='Attack an enemy unit.' emoji=<PartialEmoji animated=False name='crosshair' id=1065283238618214410> default=False>, <SelectOption label='Attack (Building)' value='Attack (Building)' description='Attack an enemy building.' emoji=<PartialEmoji animated=False name='crosshair' id=1065283238618214410> default=False>, <SelectOption label='Structure' value='Structure' description='Interact with near buildings.' emoji=<PartialEmoji animated=False name='gears' id=1068824355687112756> default=False>, <SelectOption label='Guard' value='Guard' description='Attack any enemy units within field of view.' emoji=<PartialEmoji animated=False name='⚔️' id=None> default=False>, <SelectOption label='Build' value='Build' description='Construct new buildings.' emoji=<PartialEmoji animated=False name='tool' id=1070299017587732501> default=False>, <SelectOption label='Plant' value='Plant' description='Plant seeds.' emoji=<PartialEmoji animated=False name='seeds' id=1139516070869352499> default=False>]>
Traceback (most recent call last):
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/ui/view.py", line 427, in _scheduled_task
    await item.callback(interaction)
  File "/home/rhythm/python/schwi.py/models/views.py", line 162, in callback
    await interaction.response.send_message("Enter the distance vector x y")
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/interactions.py", line 801, in send_message
    await adapter.create_interaction_response(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/webhook/async_.py", line 219, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction
WARNING    - 2023-08-11 17:15:54,694 - gateway         : Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "/home/rhythm/python/schwi.py/main.py", line 37, in <module>
    run()
  File "/home/rhythm/python/schwi.py/main.py", line 33, in run
    bot.run(settings.DISCORD_API_SECRET, root_logger=True)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/usr/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/ext/tasks/__init__.py", line 239, in _loop
    await self.coro(*args, **kwargs)
  File "/home/rhythm/python/schwi.py/cogs/world.py", line 106, in game
    db.units_collection.update_one(query, update)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/collection.py", line 1052, in update_one
    self._update_retryable(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/collection.py", line 847, in _update_retryable
    return self.__database.client._retryable_write(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1493, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1360, in _retry_with_session
    return self._retry_internal(retryable, func, session, bulk)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/_csot.py", line 106, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1401, in _retry_internal
    return func(session, sock_info, retryable)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/collection.py", line 828, in _update
    return self._update(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/collection.py", line 784, in _update
    result = sock_info.command(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/helpers.py", line 279, in inner
    return func(*args, **kwargs)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/pool.py", line 879, in command
    return command(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/network.py", line 156, in command
    reply = receive_message(sock_info, request_id)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/network.py", line 217, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/network.py", line 299, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "/usr/lib/python3.11/ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.11/ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)

ERROR      - 2023-08-11 17:16:03,947 - client          : Attempting a reconnect in 1.20s
Traceback (most recent call last):
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/client.py", line 659, in connect
    await self.ws.poll_event()
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/gateway.py", line 646, in poll_event
    raise ConnectionClosed(self.socket, shard_id=self.shard_id, code=code) from None
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 1000
INFO       - 2023-08-11 17:16:17,978 - gateway         : Shard ID None has successfully RESUMED session e6155d169bc71e1fe3338c628efa16c5.
WARNING    - 2023-08-11 17:17:08,849 - gateway         : Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "/home/rhythm/python/schwi.py/main.py", line 37, in <module>
    run()
  File "/home/rhythm/python/schwi.py/main.py", line 33, in run
    bot.run(settings.DISCORD_API_SECRET, root_logger=True)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/usr/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/ext/tasks/__init__.py", line 239, in _loop
    await self.coro(*args, **kwargs)
  File "/home/rhythm/python/schwi.py/cogs/world.py", line 108, in game
    db.fog_collection.bulk_write(fog_updates)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/_csot.py", line 106, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/collection.py", line 548, in bulk_write
    bulk_api_result = blk.execute(write_concern, session)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/bulk.py", line 514, in execute
    return self.execute_command(generator, write_concern, session)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/bulk.py", line 391, in execute_command
    client._retry_with_session(self.is_retryable, retryable_bulk, s, self)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1360, in _retry_with_session
    return self._retry_internal(retryable, func, session, bulk)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/_csot.py", line 106, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1401, in _retry_internal
    return func(session, sock_info, retryable)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/bulk.py", line 385, in retryable_bulk
    self._execute_command(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/bulk.py", line 338, in _execute_command
    result, to_send = bwc.execute(cmd, ops, client)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/message.py", line 841, in execute
    result = self.write_command(cmd, request_id, msg, to_send)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/helpers.py", line 279, in inner
    return func(*args, **kwargs)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/message.py", line 920, in write_command
    reply = self.sock_info.write_command(request_id, msg, self.codec)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/pool.py", line 965, in write_command
    reply = self.receive_message(request_id)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/pool.py", line 931, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/network.py", line 217, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/network.py", line 299, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "/usr/lib/python3.11/ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.11/ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)

WARNING    - 2023-08-11 17:17:18,855 - gateway         : Shard ID None heartbeat blocked for more than 20 seconds.
Loop thread traceback (most recent call last):
  File "/home/rhythm/python/schwi.py/main.py", line 37, in <module>
    run()
  File "/home/rhythm/python/schwi.py/main.py", line 33, in run
    bot.run(settings.DISCORD_API_SECRET, root_logger=True)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/usr/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/ext/tasks/__init__.py", line 239, in _loop
    await self.coro(*args, **kwargs)
  File "/home/rhythm/python/schwi.py/cogs/world.py", line 36, in game
    command_list = list(db.commands_collection.find())
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/cursor.py", line 1251, in next
    if len(self.__data) or self._refresh():
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/cursor.py", line 1168, in _refresh
    self.__send_message(q)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/cursor.py", line 1055, in __send_message
    response = client._run_operation(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/_csot.py", line 106, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1341, in _run_operation
    return self._retryable_read(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/_csot.py", line 106, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1465, in _retryable_read
    return func(session, server, sock_info, read_pref)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1337, in _cmd
    return server.run_operation(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/helpers.py", line 279, in inner
    return func(*args, **kwargs)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/server.py", line 116, in run_operation
    reply = sock_info.receive_message(request_id)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/pool.py", line 931, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/network.py", line 217, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/network.py", line 299, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "/usr/lib/python3.11/ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.11/ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)

ERROR      - 2023-08-11 17:17:23,897 - client          : Attempting a reconnect in 0.95s
Traceback (most recent call last):
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/client.py", line 659, in connect
    await self.ws.poll_event()
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/gateway.py", line 646, in poll_event
    raise ConnectionClosed(self.socket, shard_id=self.shard_id, code=code) from None
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 1000
INFO       - 2023-08-11 17:17:34,634 - gateway         : Shard ID None has successfully RESUMED session e6155d169bc71e1fe3338c628efa16c5.
WARNING    - 2023-08-11 17:27:26,937 - gateway         : Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "/home/rhythm/python/schwi.py/main.py", line 37, in <module>
    run()
  File "/home/rhythm/python/schwi.py/main.py", line 33, in run
    bot.run(settings.DISCORD_API_SECRET, root_logger=True)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/usr/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/discord/ext/tasks/__init__.py", line 239, in _loop
    await self.coro(*args, **kwargs)
  File "/home/rhythm/python/schwi.py/cogs/world.py", line 106, in game
    db.units_collection.update_one(query, update)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/collection.py", line 1052, in update_one
    self._update_retryable(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/collection.py", line 847, in _update_retryable
    return self.__database.client._retryable_write(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1493, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1360, in _retry_with_session
    return self._retry_internal(retryable, func, session, bulk)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/_csot.py", line 106, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1401, in _retry_internal
    return func(session, sock_info, retryable)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/collection.py", line 828, in _update
    return self._update(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/collection.py", line 784, in _update
    result = sock_info.command(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/helpers.py", line 279, in inner
    return func(*args, **kwargs)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/pool.py", line 879, in command
    return command(
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/network.py", line 156, in command
    reply = receive_message(sock_info, request_id)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/network.py", line 217, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline)
  File "/home/rhythm/python/schwi.py/venv/lib/python3.11/site-packages/pymongo/network.py", line 299, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "/usr/lib/python3.11/ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.11/ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)

WARNING    - 2023-08-11 17:27:33,600 - gateway         : Can't keep up, shard ID None websocket is 57.9s behind.
